<!-- BEGIN: Theme CSS-->
<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{{ asset('fonts/lawyer-gothic.ttf') }}" />
<link href="https://db.onlinewebfonts.com/c/54bd6780e4d295ddc5890b366eb243fb?family=GothamRndSSm-Book" rel="stylesheet" type="text/css"/>

<link rel="stylesheet" href="{{ asset('assets/vendor/fonts/boxicons.css') }}" />

<!-- Core CSS -->
<link rel="stylesheet" href="{{ asset('assets/vendor/css/core.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/vendor/css/theme-semi-dark.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/demo.css') }}" />

<link rel="stylesheet" href="{{ asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css') }}" />

<!-- Vendor Styles -->
@yield('vendor-style')


<!-- Page Styles -->
@yield('page-style')

<style>
    /* This stylesheet generated by Transfonter (https://transfonter.org) on July 5, 2017 12:36 AM */

    @font-face {
        font-family: 'Lawyer Gothic';
        src: url('{{ asset("fonts/LawyerGothic-Bold.eot") }}');
        src: local('Lawyer Gothic Bold'), local('LawyerGothic-Bold'),
            url('{{ asset("fonts/LawyerGothic-Bold.eot") }}?#iefix') format('embedded-opentype'),
            url('{{ asset("fonts/LawyerGothic-Bold.woff") }}') format('woff'),
            url('{{ asset("fonts/LawyerGothic-Bold.ttf") }}') format('truetype');
        font-weight: bold;
        font-style: normal;
    }

</style>